#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Muslims.Droid.Resource", IsApplication=true)]

namespace Muslims.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F0200A3
			public const int bg = 2130837667;
			
			// aapt resource value: 0x7F0200A4
			public const int bg_biblioteka = 2130837668;
			
			// aapt resource value: 0x7F0200A5
			public const int bg_biblioteka_blue = 2130837669;
			
			// aapt resource value: 0x7F0200A6
			public const int bg_blue = 2130837670;
			
			// aapt resource value: 0x7F020000
			public const int Conditions_2 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Conditions_2_blue = 2130837505;
			
			// aapt resource value: 0x7F0200A7
			public const int ic = 2130837671;
			
			// aapt resource value: 0x7F0200B1
			public const int icoi_prilozh_72 = 2130837681;
			
			// aapt resource value: 0x7F0200B0
			public const int ico_prilozh = 2130837680;
			
			// aapt resource value: 0x7F0200A8
			public const int ic_1 = 2130837672;
			
			// aapt resource value: 0x7F0200A9
			public const int ic_2 = 2130837673;
			
			// aapt resource value: 0x7F0200AA
			public const int ic_3 = 2130837674;
			
			// aapt resource value: 0x7F0200AB
			public const int ic_4 = 2130837675;
			
			// aapt resource value: 0x7F0200AC
			public const int ic_5 = 2130837676;
			
			// aapt resource value: 0x7F0200AD
			public const int ic_6 = 2130837677;
			
			// aapt resource value: 0x7F0200AE
			public const int ic_7 = 2130837678;
			
			// aapt resource value: 0x7F0200AF
			public const int ic_blue = 2130837679;
			
			// aapt resource value: 0x7F0200B2
			public const int kurb_1_ = 2130837682;
			
			// aapt resource value: 0x7F0200B3
			public const int kurb_2_ = 2130837683;
			
			// aapt resource value: 0x7F0200B4
			public const int kurb_3_ = 2130837684;
			
			// aapt resource value: 0x7F0200B5
			public const int kurb_4_ = 2130837685;
			
			// aapt resource value: 0x7F0200B6
			public const int kurb_5_ = 2130837686;
			
			// aapt resource value: 0x7F0200B7
			public const int logo = 2130837687;
			
			// aapt resource value: 0x7F0200B8
			public const int logo2 = 2130837688;
			
			// aapt resource value: 0x7F0200B9
			public const int logo_start = 2130837689;
			
			// aapt resource value: 0x7F0200BA
			public const int menu_bg = 2130837690;
			
			// aapt resource value: 0x7F0200BB
			public const int muslims = 2130837691;
			
			// aapt resource value: 0x7F020002
			public const int Order_1 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int Order_1_blue = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int Perpetration_3 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int Perpetration_3_blue = 2130837509;
			
			// aapt resource value: 0x7F0200BC
			public const int picture = 2130837692;
			
			// aapt resource value: 0x7F0200BD
			public const int poryadok_soversheniya = 2130837693;
			
			// aapt resource value: 0x7F020006
			public const int Prayers_5 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int Prayers_5_blue = 2130837511;
			
			// aapt resource value: 0x7F0200F8
			public const int spbt_10_ = 2130837752;
			
			// aapt resource value: 0x7F0200F9
			public const int spbt_11_ = 2130837753;
			
			// aapt resource value: 0x7F0200FA
			public const int spbt_12_ = 2130837754;
			
			// aapt resource value: 0x7F0200FB
			public const int spbt_13_ = 2130837755;
			
			// aapt resource value: 0x7F0200FC
			public const int spbt_14_ = 2130837756;
			
			// aapt resource value: 0x7F0200FD
			public const int spbt_15_ = 2130837757;
			
			// aapt resource value: 0x7F0200FE
			public const int spbt_16_ = 2130837758;
			
			// aapt resource value: 0x7F0200FF
			public const int spbt_17_ = 2130837759;
			
			// aapt resource value: 0x7F020100
			public const int spbt_18_ = 2130837760;
			
			// aapt resource value: 0x7F020101
			public const int spbt_19_ = 2130837761;
			
			// aapt resource value: 0x7F020102
			public const int spbt_1_ = 2130837762;
			
			// aapt resource value: 0x7F020103
			public const int spbt_20_ = 2130837763;
			
			// aapt resource value: 0x7F020104
			public const int spbt_21_ = 2130837764;
			
			// aapt resource value: 0x7F020105
			public const int spbt_22_ = 2130837765;
			
			// aapt resource value: 0x7F020106
			public const int spbt_23_ = 2130837766;
			
			// aapt resource value: 0x7F020107
			public const int spbt_2_ = 2130837767;
			
			// aapt resource value: 0x7F020108
			public const int spbt_3_ = 2130837768;
			
			// aapt resource value: 0x7F020109
			public const int spbt_4_ = 2130837769;
			
			// aapt resource value: 0x7F02010A
			public const int spbt_5_ = 2130837770;
			
			// aapt resource value: 0x7F02010B
			public const int spbt_6_ = 2130837771;
			
			// aapt resource value: 0x7F02010C
			public const int spbt_7_ = 2130837772;
			
			// aapt resource value: 0x7F02010D
			public const int spbt_8_ = 2130837773;
			
			// aapt resource value: 0x7F02010E
			public const int spbt_9_ = 2130837774;
			
			// aapt resource value: 0x7F0200BE
			public const int spb_10_ = 2130837694;
			
			// aapt resource value: 0x7F0200BF
			public const int spb_11_ = 2130837695;
			
			// aapt resource value: 0x7F0200C0
			public const int spb_12_ = 2130837696;
			
			// aapt resource value: 0x7F0200C1
			public const int spb_13_ = 2130837697;
			
			// aapt resource value: 0x7F0200C2
			public const int spb_14_ = 2130837698;
			
			// aapt resource value: 0x7F0200C3
			public const int spb_15_ = 2130837699;
			
			// aapt resource value: 0x7F0200C4
			public const int spb_16_ = 2130837700;
			
			// aapt resource value: 0x7F0200C5
			public const int spb_17_ = 2130837701;
			
			// aapt resource value: 0x7F0200C6
			public const int spb_18_ = 2130837702;
			
			// aapt resource value: 0x7F0200C7
			public const int spb_19_ = 2130837703;
			
			// aapt resource value: 0x7F0200C8
			public const int spb_1_ = 2130837704;
			
			// aapt resource value: 0x7F0200C9
			public const int spb_20_ = 2130837705;
			
			// aapt resource value: 0x7F0200CA
			public const int spb_21_ = 2130837706;
			
			// aapt resource value: 0x7F0200CB
			public const int spb_22_ = 2130837707;
			
			// aapt resource value: 0x7F0200CC
			public const int spb_23_ = 2130837708;
			
			// aapt resource value: 0x7F0200CD
			public const int spb_24_ = 2130837709;
			
			// aapt resource value: 0x7F0200CE
			public const int spb_25_ = 2130837710;
			
			// aapt resource value: 0x7F0200CF
			public const int spb_26_ = 2130837711;
			
			// aapt resource value: 0x7F0200D0
			public const int spb_27_ = 2130837712;
			
			// aapt resource value: 0x7F0200D1
			public const int spb_28_ = 2130837713;
			
			// aapt resource value: 0x7F0200D2
			public const int spb_29_ = 2130837714;
			
			// aapt resource value: 0x7F0200D3
			public const int spb_2_ = 2130837715;
			
			// aapt resource value: 0x7F0200D4
			public const int spb_30_ = 2130837716;
			
			// aapt resource value: 0x7F0200D5
			public const int spb_3_ = 2130837717;
			
			// aapt resource value: 0x7F0200D6
			public const int spb_4_ = 2130837718;
			
			// aapt resource value: 0x7F0200D7
			public const int spb_5_ = 2130837719;
			
			// aapt resource value: 0x7F0200D8
			public const int spb_6_ = 2130837720;
			
			// aapt resource value: 0x7F0200D9
			public const int spb_7_ = 2130837721;
			
			// aapt resource value: 0x7F0200DA
			public const int spb_8_ = 2130837722;
			
			// aapt resource value: 0x7F0200DB
			public const int spb_9_ = 2130837723;
			
			// aapt resource value: 0x7F0200DC
			public const int spb_ico_1 = 2130837724;
			
			// aapt resource value: 0x7F0200DD
			public const int spb_ico_2 = 2130837725;
			
			// aapt resource value: 0x7F0200DE
			public const int spb_ico_2010_1 = 2130837726;
			
			// aapt resource value: 0x7F0200DF
			public const int spb_ico_2010_2 = 2130837727;
			
			// aapt resource value: 0x7F0200E0
			public const int spb_ico_2010_3 = 2130837728;
			
			// aapt resource value: 0x7F0200E1
			public const int spb_ico_2010_4 = 2130837729;
			
			// aapt resource value: 0x7F0200E2
			public const int spb_ico_2010_5 = 2130837730;
			
			// aapt resource value: 0x7F0200E3
			public const int spb_ico_2010_6 = 2130837731;
			
			// aapt resource value: 0x7F0200E4
			public const int spb_ico_2010_7 = 2130837732;
			
			// aapt resource value: 0x7F0200E5
			public const int spb_ico_2011_1 = 2130837733;
			
			// aapt resource value: 0x7F0200E6
			public const int spb_ico_2011_2 = 2130837734;
			
			// aapt resource value: 0x7F0200E7
			public const int spb_ico_2011_3 = 2130837735;
			
			// aapt resource value: 0x7F0200E8
			public const int spb_ico_2011_4 = 2130837736;
			
			// aapt resource value: 0x7F0200E9
			public const int spb_ico_2011_5 = 2130837737;
			
			// aapt resource value: 0x7F0200EA
			public const int spb_ico_2011_6 = 2130837738;
			
			// aapt resource value: 0x7F0200EB
			public const int spb_ico_2011_7 = 2130837739;
			
			// aapt resource value: 0x7F0200EC
			public const int spb_ico_2012_1 = 2130837740;
			
			// aapt resource value: 0x7F0200ED
			public const int spb_ico_2012_2 = 2130837741;
			
			// aapt resource value: 0x7F0200EE
			public const int spb_ico_2012_3 = 2130837742;
			
			// aapt resource value: 0x7F0200EF
			public const int spb_ico_2012_4 = 2130837743;
			
			// aapt resource value: 0x7F0200F0
			public const int spb_ico_2012_5 = 2130837744;
			
			// aapt resource value: 0x7F0200F1
			public const int spb_ico_2012_6 = 2130837745;
			
			// aapt resource value: 0x7F0200F2
			public const int spb_ico_3 = 2130837746;
			
			// aapt resource value: 0x7F0200F3
			public const int spb_ico_4 = 2130837747;
			
			// aapt resource value: 0x7F0200F4
			public const int spb_ico_5 = 2130837748;
			
			// aapt resource value: 0x7F0200F5
			public const int spb_ico_6 = 2130837749;
			
			// aapt resource value: 0x7F0200F6
			public const int spb_ico_7 = 2130837750;
			
			// aapt resource value: 0x7F0200F7
			public const int spb_ico_8 = 2130837751;
			
			// aapt resource value: 0x7F020008
			public const int Time_4 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int Time_4_blue = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int Y2010conf_10_ = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int Y2010conf_1_ = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int Y2010conf_2_ = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int Y2010conf_3_ = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int Y2010conf_4_ = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int Y2010conf_5_ = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int Y2010conf_6_ = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int Y2010conf_7_ = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int Y2010conf_8_ = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int Y2010conf_9_ = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int Y2010iftar_1_ = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int Y2010iftar_2_ = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int Y2010iftar_3_ = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int Y2010iftar_4_ = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int Y2010kurban2_1_ = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int Y2010kurban2_2_ = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int Y2010kurban2_3_ = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int Y2010kurban2_4_ = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int Y2010kurban2_5_ = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int Y2010kurban2_6_ = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int Y2010kurban2_7_ = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int Y2010kurban2_8_ = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int Y2010kurban2_9_ = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int Y2010kurban_10_ = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int Y2010kurban_11_ = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int Y2010kurban_12_ = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int Y2010kurban_1_ = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int Y2010kurban_2_ = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int Y2010kurban_3_ = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int Y2010kurban_4_ = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int Y2010kurban_5_ = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int Y2010kurban_6_ = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int Y2010kurban_7_ = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int Y2010kurban_8_ = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int Y2010kurban_9_ = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int Y2010mdeal_1_ = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int Y2010mdeal_2_ = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int Y2010mdeal_3_ = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int Y2010port_1_ = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int Y2010port_2_ = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int Y2010port_3_ = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int Y2010port_4_ = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int Y2010port_5_ = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int Y2010port_6_ = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int Y2010port_7_ = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int Y2010uraza_1_ = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int Y2010uraza_2_ = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int Y2010uraza_3_ = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int Y2010uraza_4_ = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int Y2010uraza_5_ = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int Y2010uraza_6_ = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int Y2010uraza_7_ = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int Y2011cross_1_ = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int Y2011cross_2_ = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int Y2011cross_3_ = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int Y2011cross_4_ = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int Y2011cross_5_ = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int Y2011cross_6_ = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int Y2011cross_7_ = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int Y2011cross_8_ = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int Y2011gen_1_ = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int Y2011gen_2_ = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int Y2011gen_3_ = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int Y2011gen_4_ = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int Y2011gen_5_ = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int Y2011gen_6_ = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int Y2011kurban_1_ = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int Y2011kurban_2_ = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int Y2011kurban_3_ = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int Y2011kurban_4_ = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int Y2011kurban_5_ = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int Y2011pisc_1_ = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int Y2011pisc_2_ = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int Y2011pisc_3_ = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int Y2011pisc_4_ = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int Y2011pisc_5_ = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int Y2011pisc_6_ = 2130837590;
			
			// aapt resource value: 0x7F020057
			public const int Y2011traur_10_ = 2130837591;
			
			// aapt resource value: 0x7F020058
			public const int Y2011traur_11_ = 2130837592;
			
			// aapt resource value: 0x7F020059
			public const int Y2011traur_12_ = 2130837593;
			
			// aapt resource value: 0x7F02005A
			public const int Y2011traur_1_ = 2130837594;
			
			// aapt resource value: 0x7F02005B
			public const int Y2011traur_2_ = 2130837595;
			
			// aapt resource value: 0x7F02005C
			public const int Y2011traur_3_ = 2130837596;
			
			// aapt resource value: 0x7F02005D
			public const int Y2011traur_4_ = 2130837597;
			
			// aapt resource value: 0x7F02005E
			public const int Y2011traur_5_ = 2130837598;
			
			// aapt resource value: 0x7F02005F
			public const int Y2011traur_6_ = 2130837599;
			
			// aapt resource value: 0x7F020060
			public const int Y2011traur_7_ = 2130837600;
			
			// aapt resource value: 0x7F020061
			public const int Y2011traur_8_ = 2130837601;
			
			// aapt resource value: 0x7F020062
			public const int Y2011traur_9_ = 2130837602;
			
			// aapt resource value: 0x7F020063
			public const int Y2011tukaev_1_ = 2130837603;
			
			// aapt resource value: 0x7F020064
			public const int Y2011tukaev_2_ = 2130837604;
			
			// aapt resource value: 0x7F020065
			public const int Y2011tukaev_3_ = 2130837605;
			
			// aapt resource value: 0x7F020066
			public const int Y2011viborg_10_ = 2130837606;
			
			// aapt resource value: 0x7F020067
			public const int Y2011viborg_11_ = 2130837607;
			
			// aapt resource value: 0x7F020068
			public const int Y2011viborg_12_ = 2130837608;
			
			// aapt resource value: 0x7F020069
			public const int Y2011viborg_1_ = 2130837609;
			
			// aapt resource value: 0x7F02006A
			public const int Y2011viborg_2_ = 2130837610;
			
			// aapt resource value: 0x7F02006B
			public const int Y2011viborg_3_ = 2130837611;
			
			// aapt resource value: 0x7F02006C
			public const int Y2011viborg_4_ = 2130837612;
			
			// aapt resource value: 0x7F02006D
			public const int Y2011viborg_5_ = 2130837613;
			
			// aapt resource value: 0x7F02006E
			public const int Y2011viborg_6_ = 2130837614;
			
			// aapt resource value: 0x7F02006F
			public const int Y2011viborg_7_ = 2130837615;
			
			// aapt resource value: 0x7F020070
			public const int Y2011viborg_8_ = 2130837616;
			
			// aapt resource value: 0x7F020071
			public const int Y2011viborg_9_ = 2130837617;
			
			// aapt resource value: 0x7F020072
			public const int Y2012miting_1_ = 2130837618;
			
			// aapt resource value: 0x7F020073
			public const int Y2012miting_2_ = 2130837619;
			
			// aapt resource value: 0x7F020074
			public const int Y2012miting_3_ = 2130837620;
			
			// aapt resource value: 0x7F020075
			public const int Y2012miting_4_ = 2130837621;
			
			// aapt resource value: 0x7F020076
			public const int Y2012miting_5_ = 2130837622;
			
			// aapt resource value: 0x7F020077
			public const int Y2012miting_6_ = 2130837623;
			
			// aapt resource value: 0x7F020078
			public const int Y2012pisc_1_ = 2130837624;
			
			// aapt resource value: 0x7F020079
			public const int Y2012pisc_2_ = 2130837625;
			
			// aapt resource value: 0x7F02007A
			public const int Y2012pisc_3_ = 2130837626;
			
			// aapt resource value: 0x7F02007B
			public const int Y2012pisc_4_ = 2130837627;
			
			// aapt resource value: 0x7F02007C
			public const int Y2012proshanie_10_ = 2130837628;
			
			// aapt resource value: 0x7F02007D
			public const int Y2012proshanie_11_ = 2130837629;
			
			// aapt resource value: 0x7F02007E
			public const int Y2012proshanie_12_ = 2130837630;
			
			// aapt resource value: 0x7F02007F
			public const int Y2012proshanie_13_ = 2130837631;
			
			// aapt resource value: 0x7F020080
			public const int Y2012proshanie_14_ = 2130837632;
			
			// aapt resource value: 0x7F020081
			public const int Y2012proshanie_1_ = 2130837633;
			
			// aapt resource value: 0x7F020082
			public const int Y2012proshanie_2_ = 2130837634;
			
			// aapt resource value: 0x7F020083
			public const int Y2012proshanie_3_ = 2130837635;
			
			// aapt resource value: 0x7F020084
			public const int Y2012proshanie_4_ = 2130837636;
			
			// aapt resource value: 0x7F020085
			public const int Y2012proshanie_5_ = 2130837637;
			
			// aapt resource value: 0x7F020086
			public const int Y2012proshanie_6_ = 2130837638;
			
			// aapt resource value: 0x7F020087
			public const int Y2012proshanie_7_ = 2130837639;
			
			// aapt resource value: 0x7F020088
			public const int Y2012proshanie_8_ = 2130837640;
			
			// aapt resource value: 0x7F020089
			public const int Y2012proshanie_9_ = 2130837641;
			
			// aapt resource value: 0x7F02008A
			public const int Y2012sabantuy_1_ = 2130837642;
			
			// aapt resource value: 0x7F02008B
			public const int Y2012sabantuy_2_ = 2130837643;
			
			// aapt resource value: 0x7F02008C
			public const int Y2012sabantuy_3_ = 2130837644;
			
			// aapt resource value: 0x7F02008D
			public const int Y2012sabantuy_4_ = 2130837645;
			
			// aapt resource value: 0x7F02008E
			public const int Y2012sabantuy_5_ = 2130837646;
			
			// aapt resource value: 0x7F02008F
			public const int Y2012soviet_1_ = 2130837647;
			
			// aapt resource value: 0x7F020090
			public const int Y2012soviet_2_ = 2130837648;
			
			// aapt resource value: 0x7F020091
			public const int Y2012soviet_3_ = 2130837649;
			
			// aapt resource value: 0x7F020092
			public const int Y2012soviet_4_ = 2130837650;
			
			// aapt resource value: 0x7F020093
			public const int Y2012tavrich_1_ = 2130837651;
			
			// aapt resource value: 0x7F020094
			public const int Y2012tavrich_2_ = 2130837652;
			
			// aapt resource value: 0x7F020095
			public const int Y2012tavrich_3_ = 2130837653;
			
			// aapt resource value: 0x7F020096
			public const int Y2012tavrich_4_ = 2130837654;
			
			// aapt resource value: 0x7F020097
			public const int Y2013_10_ = 2130837655;
			
			// aapt resource value: 0x7F020098
			public const int Y2013_1_ = 2130837656;
			
			// aapt resource value: 0x7F020099
			public const int Y2013_2_ = 2130837657;
			
			// aapt resource value: 0x7F02009A
			public const int Y2013_3_ = 2130837658;
			
			// aapt resource value: 0x7F02009B
			public const int Y2013_4_ = 2130837659;
			
			// aapt resource value: 0x7F02009C
			public const int Y2013_5_ = 2130837660;
			
			// aapt resource value: 0x7F02009D
			public const int Y2013_6_ = 2130837661;
			
			// aapt resource value: 0x7F02009E
			public const int Y2013_7_ = 2130837662;
			
			// aapt resource value: 0x7F02009F
			public const int Y2013_8_ = 2130837663;
			
			// aapt resource value: 0x7F0200A0
			public const int Y2013_9_ = 2130837664;
			
			// aapt resource value: 0x7F0200A1
			public const int Y2014_1_ = 2130837665;
			
			// aapt resource value: 0x7F0200A2
			public const int Y2014_2_ = 2130837666;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7F060002
			public const int channel_description = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int channel_name = 2131099651;
			
			// aapt resource value: 0x7F060001
			public const int Hello = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppCompatDialogStyle = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MainTheme = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MainTheme_Base = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
